<?php
header("Content-type: text/html; charset=utf-8");
return array(
array('time'=>mktimes(2014,1,13,12,42),'type'=>'sql','sql'=>"ALTER TABLE `{tableprefix}lottery_record` ADD `sendtime` INT( 11 ) NOT NULL DEFAULT '0'",'des'=>'...'),
array('time'=>mktimes(2014,1,13,12,41),'type'=>'sql','sql'=>"ALTER TABLE `{tableprefix}lottery_record` ADD `sendstutas` TINYINT( 1 ) NOT NULL DEFAULT '0' AFTER `id` ",'des'=>'...'),
array('time'=>mktimes(2014,1,13,12,40),'type'=>'sql','sql'=>"ALTER TABLE `{tableprefix}member_card_integral` CHANGE `info` `info` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL",'des'=>'...'),
array('time'=>mktimes(2014,1,13,12,39),'type'=>'sql','sql'=>"ALTER TABLE `{tableprefix}member_card_coupon` CHANGE `info` `info` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL",'des'=>'...'),
array('time'=>mktimes(2014,1,10,12,39),'type'=>'sql','sql'=>"ALTER TABLE `{tableprefix}wxuser` ADD `color_id` MEDIUMINT( 4 ) NOT NULL DEFAULT '0' AFTER `province`",'des'=>'...'),
array('time'=>mktimes(2014,1,10,12,38),'type'=>'sql','sql'=>"ALTER TABLE `{tableprefix}diymen_class` ADD `url` VARCHAR( 100 ) NOT NULL DEFAULT '' AFTER `sort`",'des'=>'...'),
array('time'=>mktimes(2014,1,10,12,37),'type'=>'sql','sql'=>"ALTER TABLE `{tableprefix}reply` CHANGE `wecha_id` `wecha_id` VARCHAR( 60 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''",'des'=>'...'),
array('time'=>mktimes(2014,1,7,18,6),'type'=>'sql','sql'=>"ALTER TABLE `{tableprefix}home` ADD `apiurl` VARCHAR( 200 ) NOT NULL DEFAULT '' AFTER `info`",'des'=>'...'),
array('time'=>mktimes(2014,1,7,18,5),'type'=>'sql','sql'=>"ALTER TABLE  `{tableprefix}estate` ADD  `video` VARCHAR( 200 ) NULL AFTER  `banner`",'des'=>'...'),
array('time'=>mktimes(2014,1,7,18,4),'type'=>'sql','sql'=>"ALTER TABLE `{tableprefix}estate` CHANGE `place` `place` VARCHAR( 80 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''",'des'=>'...'),
array('time'=>mktimes(2014,1,6,14,24),'type'=>'sql','sql'=>"ALTER TABLE `{tableprefix}files` CHANGE `type` `type` VARCHAR( 20 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''",'des'=>'...'),
array('time'=>mktimes(2014,1,5,16,4),'type'=>'sql','sql'=>"ALTER TABLE `{tableprefix}flash` ADD `tip` SMALLINT( 2 ) NOT NULL DEFAULT '1' AFTER `info`,ADD INDEX ( `tip` )",'des'=>'...'),
array('time'=>mktimes(2014,1,4,16,4),'type'=>'sql','sql'=>"ALTER TABLE `{tableprefix}reservation` ADD `addtype` VARCHAR( 20 ) NOT NULL DEFAULT 'house_book' AFTER `picurl`",'des'=>'...'),
array('time'=>mktimes(2014,1,4,16,3),'type'=>'sql','sql'=>"ALTER TABLE  `{tableprefix}estate_impress` ADD `token` VARCHAR( 30 ) NOT NULL DEFAULT '' AFTER `id`",'des'=>'...'),
array('time'=>mktimes(2014,1,4,16,2),'type'=>'sql','sql'=>"ALTER TABLE `{tableprefix}estate_expert`  ADD `token` VARCHAR( 30 ) NOT NULL DEFAULT '' AFTER `id`",'des'=>'...'),
array('time'=>mktimes(2014,1,4,15,59),'type'=>'sql','sql'=>"ALTER TABLE `{tableprefix}userinfo` ADD `bornyear` VARCHAR( 4 ) NOT NULL DEFAULT '' AFTER `tel`,ADD `bornmonth` VARCHAR( 4 ) NOT NULL DEFAULT '' AFTER `bornyear`,ADD `bornday` VARCHAR( 4 ) NOT NULL DEFAULT '' AFTER `bornmonth`",'des'=>'...'),
array('time'=>mktimes(2014,1,2,20,46),'type'=>'sql','sql'=>"ALTER TABLE `{tableprefix}member_card_vip` ADD `usetime` INT( 10 ) NOT NULL DEFAULT '0' AFTER `info`",'des'=>'...'),
array('time'=>mktimes(2014,1,2,20,45),'type'=>'sql','sql'=>"ALTER TABLE `{tableprefix}member_card_integral` ADD `usetime` INT( 10 ) NOT NULL DEFAULT '0' AFTER `info`",'des'=>'...'),
array('time'=>mktimes(2014,1,2,20,44),'type'=>'sql','sql'=>"ALTER TABLE `{tableprefix}member_card_coupon` ADD `usetime` INT( 10 ) NOT NULL DEFAULT '0' AFTER `info`",'des'=>'...'),
array('time'=>mktimes(2014,1,2,20,43),'type'=>'sql','sql'=>"ALTER TABLE `{tableprefix}users` ADD `attachmentsize` INT( 10 ) NOT NULL DEFAULT '0' AFTER `id`",'des'=>'...'),
array('time'=>mktimes(2013,12,31,22,59),'type'=>'sql','sql'=>"ALTER TABLE `{tableprefix}userinfo` ADD `expensetotal` INT( 10 ) NOT NULL DEFAULT '0' AFTER `total_score`",'des'=>'...'),
array('time'=>mktimes(2013,12,31,22,51),'type'=>'sql','sql'=>"ALTER TABLE `{tableprefix}userinfo` ADD `total_score` INT( 10 ) NOT NULL DEFAULT '0' AFTER `id`",'des'=>'...'),
array('time'=>mktimes(2013,12,30,22,51),'type'=>'sql','sql'=>"ALTER TABLE `{tableprefix}api` ADD `type` SMALLINT( 2 ) NOT NULL DEFAULT '1' AFTER `id`",'des'=>'...'),
array('time'=>mktimes(2013,12,30,22,50),'type'=>'sql','sql'=>"ALTER TABLE `{tableprefix}api` ADD `is_colation` SMALLINT( 2 ) NOT NULL DEFAULT '1' AFTER `id` ,
ADD `colation_keyword` VARCHAR( 100 ) NOT NULL DEFAULT '' AFTER `is_colation`",'des'=>'...'),
array('time'=>mktimes(2013,12,30,22,49),'type'=>'sql','sql'=>"ALTER TABLE `{tableprefix}api` ADD `keyword` VARCHAR( 100 ) NOT NULL DEFAULT '' AFTER `id`",'des'=>'...'),
array('time'=>mktimes(2013,12,30,22,48),'type'=>'sql','sql'=>"ALTER TABLE `{tableprefix}api` ADD `status` TINYINT( 1 ) NOT NULL DEFAULT '0' AFTER `time`",'des'=>'...'),
array('time'=>mktimes(2013,12,28,22,53),'type'=>'sql','sql'=>"CREATE TABLE IF NOT EXISTS `{tableprefix}home_background` (`id` int(10) NOT NULL AUTO_INCREMENT,`token` varchar(60) NOT NULL DEFAULT '',`picurl` varchar(200) NOT NULL DEFAULT '',`url` varchar(200) NOT NULL DEFAULT '',`taxis` int(10) NOT NULL DEFAULT '0',PRIMARY KEY (`id`),KEY `token` (`token`)) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1",'des'=>'...'),
array('time'=>mktimes(2013,12,28,12,28),'type'=>'sql','sql'=>"ALTER TABLE `{tableprefix}home` ADD `logo` VARCHAR( 200 ) NOT NULL DEFAULT '' AFTER `copyright`",'des'=>'...'),
array('time'=>mktimes(2013,12,27,11,22),'type'=>'sql','sql'=>"ALTER TABLE `tp_vote_item` CHANGE `startpicurl` `startpicurl` VARCHAR( 200 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',CHANGE `tourl` `tourl` VARCHAR( 200 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT ''",'des'=>'...'));
?>